AllCops:
  TargetRubyVersion: 2.3

Style/Documentation:
  Enabled: false

Style/MethodMissing:
  Exclude:
    - lib/json_factory/json_builder.rb

Style/ClassVars:
  Exclude:
    - lib/json_factory/json_builder.rb

Metrics/ClassLength:
  Max: 150

Metrics/LineLength:
  Max: 140
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - examples/**/*

Lint/ShadowingOuterLocalVariable:
  Exclude:
    - spec/**/*


